### Examples of calls to GitHub REST API



### User: aistrate

###
https://api.github.com/users/aistrate

### from property "repos_url"
https://api.github.com/users/aistrate/repos

### from HTTP header "Link", rel="next"
https://api.github.com/user/170662/repos?page=2

### the most usable form
https://api.github.com/users/aistrate/repos?page=1

### per_page default is 30, max is 100
https://api.github.com/users/aistrate/repos?page=1&per_page=100

### one repo
https://api.github.com/repos/aistrate/RegexParser



### User: facebook

### user (property "public_repos" shows repo count)
https://api.github.com/users/facebook

### repos (followed by page=2, etc.)
https://api.github.com/users/facebook/repos?page=1&per_page=100&sort=pushed



### Organizations: microsoft, google, netflix, github, amzn, aws, reddit,
###                airbnb, shopify, RedHatOfficial, ibm, intel, apple,
###                twitter, sap, tensorflow, nodejs, graphql, gatsbyjs,
###                JetBrains, ghc
### People: rmeoc, gaearon, shanselman, fabpot, andrew, taylorotwell,
###         Rich-Harris, ayende, kentcdodds, jskeet, yyx990803, sebmarkbage,
###         octocat, mojombo, wycats, lattner, lexfridman, serras, rtfeldman

https://api.github.com/users/microsoft

###

https://api.github.com/user/1



### Rate limit: 60 requests/hour
### Reset time: new Date(n * 1000), where n is the 'X-RateLimit-Reset' HTTP header

https://api.github.com/rate_limit
